# Generated by Django 4.1.7 on 2023-03-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftlogmodel',
            name='good',
        ),
        migrations.RemoveField(
            model_name='craftlogmodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='craftlogmodel',
            name='readtext',
        ),
    ]
