# Generated by Django 4.1.6 on 2023-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0002_remove_craftlogmodel_good_remove_craftlogmodel_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftlogmodel',
            name='filetype',
            field=models.TextField(default='写真'),
        ),
    ]
