# Generated by Django 4.1.6 on 2023-03-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0003_craftlogmodel_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftlogmodel',
            name='filetype',
            field=models.TextField(default='pic'),
        ),
    ]
