# Generated by Django 4.1.6 on 2023-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0004_alter_craftlogmodel_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftlogmodel',
            name='craftimage',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='craftlogmodel',
            name='filetype',
            field=models.TextField(default='picture '),
        ),
    ]
