# Generated by Django 4.1.6 on 2023-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0005_alter_craftlogmodel_craftimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftlogmodel',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='craftlogmodel',
            name='filetype',
            field=models.TextField(default='picture'),
        ),
    ]
