# Generated by Django 4.1.7 on 2023-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftlogapp', '0006_craftlogmodel_storage_alter_craftlogmodel_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftlogmodel',
            name='craftimage',
            field=models.FileField(upload_to='craftimage'),
        ),
    ]
